# Safer Parks: Capturing perceptions of safety using open data

In [1]:
import pandas as pd
import geopandas as gpd
import fiona
import osmnx as ox
from shapely.ops import unary_union
import re
import folium

In [2]:
# read in safer_parks_functions - see notebook for more details on functions
%run safer_parks_functions.ipynb

### Local Authoirty Approach

This analysis is designed to be run on a local authority by local authority basis as data availability tends to vary by local authority. We use [May 2024 Local Authority District (LAD) data](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://geoportal.statistics.gov.uk/datasets/ons::local-authority-districts-may-2024-boundaries-uk-bfe-2/about&ved=2ahUKEwi83bT-pJGOAxWBUUEAHSA-NZsQFnoECAoQAQ&usg=AOvVaw3nYML7UR9GdX1gnUYTH8uz), however this can be updated as and when boundaries change. It is also possible to edit the code to change the geographies used by choosing a different shapefile boundary - e.g. focus on an entire unitary authority or metropolitan area, or focus on a specific town or village.

## Defining park boundaries

Formal park boundary data may exist and be openly avialable for some planing or administrative areas, but often this data is not publicly available or formally defined. We define a process for defining public green space using two different data sources: OS Open Greenspace and Openstreet map. Both sources have their advantages and disadvatages, as outlined in the sections below.

We recommend comparing OS and Openstreetmap data in the UK. Outside the UK we recommend using Openstreet map unless a comparative alternative is available in your region. 



### OS Open Greenspace

In Great Britain the Ordanace Survey provide 'OS Open Greenspace'-  'Covering a range of greenspaces in urban and rural areas including playing fields, sports’ facilities, play areas and allotments.' The data is provided as polygons of the greenspace areas themseleves and entry points to the greensapce site as point data. 

## Openstreetmap Greenspace data


## Comparing Greenspace data 


### Parks in Bradford
In Bradford https://bradforddistrictparks.org/ provides data on formally recognised parks and greenspaces in Bradford. We web-scraped the parks website to get further information on parks faciltiies and define 'formal' aprks and greenspaces within Bradford.




https://osdatahub.os.uk/downloads/open/OpenGreenspace

In [3]:
# read in OS Open Greenspace data
opgrsp_path = "../data_downloads/opgrsp_gpkg_gb/Data/opgrsp_gb.gpkg"

print(fiona.listlayers(opgrsp_path))
os_greenspace_access =gpd.read_file(opgrsp_path, layer ='access_point')
os_greenspace_site =gpd.read_file(opgrsp_path, layer ='greenspace_site')

['access_point', 'greenspace_site']

In [4]:
# read in local authority shapefile 
LAD_path = "../data_downloads/Local_Authority_Districts_May_2024_Boundaries_UK_BFE_-5285665645137523111.geojson"

LAD_2024 =gpd.read_file(LAD_path)

In [5]:
# get OS greenspaces sites in Bradford LAD
greenspace_sites_bradford = subset_to_LAD(LAD_gdf=LAD_2024, LAD_column_name='LAD24NM', LAD_name='Bradford', data_to_subset=os_greenspace_site)
# # combine greenspace sites that intersect or touch into one polygon
# greenspace_sites_bradford = merge_touching_or_intersecting_polygons(greenspace_sites_bradford)
# greenspace_sites_bradford = merge_touching_or_intersecting_polygons(greenspace_sites_bradford)
greenspace_sites_bradford

,id,function,distinctive_name_1,distinctive_name_2,distinctive_name_3,distinctive_name_4,geometry
1,0A0C1723-E2A4-4FA1-B127-F73A7954FB7B,Public Park Or Garden,Shay Grange Crematorium,None,None,None,"MULTIPOLYGON (((413213.450 436356.550, 412835...."
151,2BE88DCC-827A-7FED-E063-AAEFA00A0EDD,Public Park Or Garden,None,None,None,None,"MULTIPOLYGON (((411387.950 437193.900, 411383...."
163,2BE88DCC-83BB-7FED-E063-AAEFA00A0EDD,Play Space,None,None,None,None,"MULTIPOLYGON (((403185.260 444445.820, 403177...."
605,2BE88DCC-D52D-7FED-E063-AAEFA00A0EDD,Other Sports Facility,None,None,None,None,"MULTIPOLYGON (((417825.010 434672.350, 417828...."
754,2BE88DCC-F082-7FED-E063-AAEFA00A0EDD,Play Space,Attock Park,None,None,None,"MULTIPOLYGON (((418208.790 433169.630, 418211...."
...,...,...,...,...,...,...,...
161497,2BE88F5F-A26E-7FED-E063-AAEFA00A0EDD,Playing Field,None,None,None,None,"MULTIPOLYGON (((411672.850 437052.390, 411676...."
161534,2BE88F5F-AA93-7FED-E063-AAEFA00A0EDD,Other Sports Facility,None,None,None,None,"MULTIPOLYGON (((413680.210 431865.180, 413682...."
161759,2BE88F5F-D91C-7FED-E063-AAEFA00A0EDD,Public Park Or Garden,None,None,None,None,"MULTIPOLYGON (((418047.600 430223.370, 418052...."
161827,2BE88F5F-E527-7FED-E063-AAEFA00A0EDD,Public Park Or Garden,None,None,None,None,"MULTIPOLYGON (((414592.290 428702.530, 414583...."
161953,EE031128-5137-4B16-A2A9-EF1B593B8A04,Other Sports Facility,Cottingley Manor,None,None,None,"MULTIPOLYGON (((411925.750 437140.380, 411953...."

In [6]:
# get OS greenspaces access points in Bradford LAD
greenspace_access_bradford = subset_to_LAD(LAD_gdf=LAD_2024, LAD_column_name='LAD24NM', LAD_name='Bradford', data_to_subset=os_greenspace_access)
greenspace_access_bradford.explore()

In [7]:
##### Uncomment code to define GS using OSM instead od the OS Open Greenspace data, 
###### replace place name or polygon with area of interest 


# get OSM greenspaces
## Either using a placename or an shapefile to define the spatial limits of the data

# Define the tags for i.e. parks, woodlands, and scrublands
tags = {
    'leisure': ['park'],
    'landuse': ['forest', 'meadow'],
    'natural': ['wood', 'scrub']
}
################################################################################
#### Get the geometries for the specified place name and tags ####

# # Define the place name
# place_name = "Bradford, West Yorkshire, England"
# # get OSM geometries from palcename
# gdf = ox.geometries_from_place(place_name, tags)

############################ OR ################################################
#### Get the geometries for the specified polygon and tags ####

# define LAD of interest e.g. Bradford
bradford = LAD_2024.loc[LAD_2024['LAD24NM']=='Bradford',:]
# get OSM geometries from polygon boundary 
gdf = ox.geometries_from_polygon(bradford.to_crs("EPSG:4326").unary_union, tags)

################################################################################
# # Filter the geometries to include only parks, woodlands, and scrublands
osm_greenspace= gdf[gdf['leisure'].isin(['park'])|
                             gdf['landuse'].isin(['forest', 'meadow']) | 
                             gdf['natural'].isin(['wood', 'scrub'])].reset_index()

#osm_greenspace = merge_touching_or_intersecting_polygons(osm_greenspace)
osm_greenspace

/tmp/ipykernel_1071/499009049.py:28: FutureWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in the v2.0.0 release. See the OSMnx v2 migration guide: https://github.com/gboeing/osmnx/issues/1123
  gdf = ox.geometries_from_polygon(bradford.to_crs("EPSG:4326").unary_union, tags)

,element_type,osmid,access,barrier,geometry,source,name,addr:city,addr:housenumber,addr:postcode,...,source:alt_name,landcover,addr:housename,addr:village,source:geometry,historic:ref:1835_tithe_award,sport,fixme,ways,type
0,way,4472848,NaN,NaN,"POLYGON ((-1.74235 53.91227, -1.74210 53.91220...",NaN,Burley Village Green,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,way,4483806,NaN,NaN,"POLYGON ((-1.74985 53.91496, -1.74974 53.91512...",NaN,Victoria Park,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,way,4535372,NaN,NaN,"POLYGON ((-1.81990 53.92424, -1.81964 53.92424...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,way,4535557,NaN,NaN,"POLYGON ((-1.82648 53.92484, -1.82659 53.92463...",NaN,Canker Well,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,way,4536859,NaN,NaN,"POLYGON ((-1.82357 53.92632, -1.82360 53.92627...",interpolation;Bing,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3149,relation,16458862,NaN,NaN,"POLYGON ((-1.78064 53.92493, -1.78056 53.92494...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[91889679, 1214074937]",multipolygon
3150,relation,16493384,NaN,NaN,"POLYGON ((-1.75957 53.92112, -1.75960 53.92115...",Bing,Jerry Holme,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[988606691, 272999006]",multipolygon
3151,relation,16618634,NaN,NaN,"POLYGON ((-1.75531 53.89982, -1.75465 53.90013...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[1219327737, 1219327738]",multipolygon
3152,relation,17373549,NaN,NaN,"POLYGON ((-1.76340 53.86633, -1.76274 53.86657...",NaN,Hawksworth Spring,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[1160819168, 1265257477]",multipolygon
3153,relation,18547922,NaN,NaN,"POLYGON ((-1.74338 53.75393, -1.74356 53.75349...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[1351022543, 1226986189]",multipolygon

In [8]:
# Get OS greenspace cols to join
os_gs_to_join =greenspace_sites_bradford[['distinctive_name_1','function','id','geometry']]
os_gs_to_join.columns = ['Name (OS)', 'Type (OS)', 'OS ID', 'geometry' ]


# Get OSM greenspace cols to join
# combine OSM tags into one value
osm_greenspace['Type (OSM)'] =osm_greenspace[['natural', 'leisure', 'landuse']].apply(lambda x: ', '.join(sorted(x.dropna().astype(str))),axis=1)

osm_gs_to_join = osm_greenspace[['name','Type (OSM)','osmid','geometry']]
osm_gs_to_join.columns = ['Name (OSM)', 'Type (OSM)', 'OSM ID', 'geometry' ]

# change crs before joining
osm_gs_to_join= osm_gs_to_join.to_crs(os_gs_to_join.crs)
# append OSM data to OS data
os_osm_greenspace_bradford =pd.concat([os_gs_to_join,osm_gs_to_join])

# unify greenspace geographies, keepign type data
os_osm_greenspace_bradford =merge_touching_or_intersecting_polygons_condense(os_osm_greenspace_bradford)

# remove duplicate information in variables, generated during process of combining into one geometry
os_osm_greenspace_bradford['Name (OS)'] =os_osm_greenspace_bradford['Name (OS)'].apply(lambda x: ', '.join(sorted(set(map(str.strip, str(x).split(','))))) if pd.notnull(x) else x).apply(lambda x: re.sub(r'(?<!\w),', '', x))
os_osm_greenspace_bradford['Name (OSM)'] =os_osm_greenspace_bradford['Name (OSM)'].apply(lambda x: ', '.join(sorted(set(map(str.strip, str(x).split(','))))) if pd.notnull(x) else x).apply(lambda x: re.sub(r'(?<!\w),', '', x))

os_osm_greenspace_bradford['Type (OS)'] =os_osm_greenspace_bradford['Type (OS)'].apply(lambda x: ', '.join(sorted(set(map(str.strip, str(x).split(', '))))) if pd.notnull(x) else x).apply(lambda x: re.sub(r'(?<!\w),', '', x))
os_osm_greenspace_bradford['Type (OSM)'] =os_osm_greenspace_bradford['Type (OSM)'].apply(lambda x: ', '.join(sorted(set(map(str.strip, str(x).split(', '))))) if pd.notnull(x) else x).apply(lambda x: re.sub(r'(?<!\w),', '', x))

os_osm_greenspace_bradford['OS ID'] = os_osm_greenspace_bradford['OS ID'].apply(lambda x: ', '.join(sorted(set(map(str.strip, str(x).split(', '))))) if pd.notnull(x) else x).apply(lambda x: re.sub(r'(?<!\w),', '', x))
os_osm_greenspace_bradford['OSM ID'] = os_osm_greenspace_bradford['OSM ID'].apply(lambda x: ', '.join(sorted(set(map(str.strip, str(x).split(', '))))) if pd.notnull(x) else x).apply(lambda x: re.sub(r'(?<!\w),', '', x))

In [9]:
os_osm_greenspace_bradford.explore()

/home/maeve/miniforge3/envs/parks-dev-env-old/lib/python3.12/site-packages/folium/features.py:1204: UserWarning: GeoJsonTooltip is not configured to render for GeoJson GeometryCollection geometries. Please consider reworking these features: [{'Name (OS)': '', 'Type (OS)': ' ', 'OS ID': ' ', 'Name (OSM)': ' Cringles Plantation, Little Sea Moor', 'Type (OSM)': 'meadow, wood', 'OSM ID': '1334814971.0, 1354777437.0, 1355127608.0, 1355127613.0, 1355127624.0, 1355127626.0, 1355127630.0, 1355127648.0, 1355127654.0, 1355127658.0, 1355127660.0, 1359967022.0, 1359968748.0, 1359968752.0, 1359968754.0, 1359979811.0, 1360767488.0, 1360767493.0, 1360767497.0, 1360767499.0, 1360767505.0, 1360767508.0, 1360767512.0, 1360767523.0, 1360767528.0, 1360769053.0, 1360769055.0, 1360769056.0, 1360769057.0, 1360769060.0, 1360769061.0, 1360769064.0, 1360769065.0, 1360769066.0, 1360769067.0, 1360769069.0, 1361072023.0, 1361072024.0, 1361072026.0, 1361072028.0, 1361072032.0, 1361072036.0, 1361072038.0, 1361072048.0, 1361072050.0, 1361072052.0, 1361072053.0, 1361072054.0, 1361072055.0, 1361072060.0, 1361072061.0, 1361072064.0, 1361072065.0, 207466323.0, 800327048.0, 800328184.0, 800329856.0, 800334559.0, 95195238.0'}] to MultiPolygon for full functionality.
https://tools.ietf.org/html/rfc7946#page-9
  warnings.warn(

In [10]:
# Defining parks

bradford_parks_data = '../data_downloads/bradford_district_parks.geojson'

# Data scraped from: 'https://bradforddistrictparks.org/park/page/'
# See Bradford_parks_info.ipynb
bd_parks= gpd.read_file(bradford_parks_data)
bd_parks.explore()

In [11]:
# os_osm_greenspace_bradford_buffer = os_osm_greenspace_bradford
# os_osm_greenspace_bradford_buffer['geometry'] =os_osm_greenspace_bradford_buffer.buffer(50)


# test =gpd.sjoin(os_osm_greenspace_bradford_buffer, bd_parks.to_crs(os_osm_greenspace_bradford_buffer.crs), predicate='intersects', how='left')

# test.loc[test['Park Name'].isna()==True, 'BMDC_park']= 'No'
# test.loc[test['Park Name'].isna()==False, 'BMDC_park']= 'BMDC Park'

In [12]:
##### combine bradford parks data from website with OSM and OS combined greensapce data
# cerate a copy
bd_parks_polygon= bd_parks
# remove geom column (for now)
bd_parks_polygon =bd_parks_polygon.drop(columns=['geometry'])
bd_parks_polygon = bd_parks_polygon.reset_index()

# idenitfy where bradford park anmes exactly match the OS or OSM Name
bd_parks_polygon_1 =bd_parks_polygon.merge(os_osm_greenspace_bradford, right_on='Name (OS)',left_on='Park Name', how='left')
bd_parks_polygon_2 =bd_parks_polygon.merge(os_osm_greenspace_bradford, right_on='Name (OSM)',left_on='Park Name', how='left')

# remove null rows after join
bd_parks_polygon_1 =bd_parks_polygon_1.dropna(subset=['OS ID','OSM ID'])
bd_parks_polygon_2 =bd_parks_polygon_2.dropna(subset=['OS ID','OSM ID'])

# combine the exact match data into one geodataframe
bd_parks_polygon_1_2 =gpd.GeoDataFrame(pd.concat([bd_parks_polygon_1,bd_parks_polygon_2]).drop_duplicates('index'))

# use the exact match data to identify the remiaingn bmdc parks without os or osm greenspace data
bd_parks_polygon_3 =bd_parks_polygon[~bd_parks_polygon['index'].isin(bd_parks_polygon_1_2['index'])]
# and save as bd_parks_polygon_3
bd_parks_polygon_3 =gpd.GeoDataFrame(bd_parks_polygon_3, geometry=gpd.points_from_xy(bd_parks_polygon_3.Longitude, bd_parks_polygon_3.Latitude, crs="EPSG:4326"))

# ## Uncomment if want to do sjoin on buffer in future
# os_osm_greenspace_bradford_buffer = os_osm_greenspace_bradford
# os_osm_greenspace_bradford_buffer['geometry'] =os_osm_greenspace_bradford.buffer(30)

# spaially join bmdc park points to os and OSM greenspace data
bd_parks_polygon_3 =gpd.sjoin(bd_parks_polygon_3.to_crs(os_osm_greenspace_bradford.crs),os_osm_greenspace_bradford, predicate='intersects', how='left')

###### come back to later- bmdc parks on website that do not have an easily identifiable open counterpart #####
#(either due to lack of spatial info on bmdc, innacurate locaiton or incosnsitent naming)
bd_parks_polygon_4 =bd_parks_polygon_3[bd_parks_polygon_3['index_right'].isna()]


bd_parks_polygon_3=bd_parks_polygon_3[~bd_parks_polygon_3['index_right'].isna()]
# define bradford parks as those with an exact name or spatial join match (43/71 parks, a remaining 10 aprks do have long/lat info)
bradford_parks_gdf =gpd.GeoDataFrame(pd.concat([bd_parks_polygon_1,bd_parks_polygon_2,bd_parks_polygon_3]).drop_duplicates('index'))

In [13]:
bradford_parks_gdf

,index,Park Name,Park URL,Location,Opening Hours,Latitude,Longitude,Car parking,River,Walking routes,...,Miniature railway,Park features str,Name (OS),Type (OS),OS ID,Name (OSM),Type (OSM),OSM ID,geometry,index_right
5,5,Russell Hall Park,https://bradforddistrictparks.org/park/russell...,"Russell Hall Ave, Queensbury, BD13 2AL","Open 24 hours a day, all year round",53.7652724,-1.8488896,0,0,0,...,0,"5-a-side football pitch, Bowling green, Childr...",Russell Hall Park,"Bowling Green, Play Space, Playing Field","2BE88E26-152D-7FED-E063-AAEFA00A0EDD, 2BE88E26...",Russell Hall Park,park,200908882.0,"POLYGON ((575797.160 5957983.962, 575793.517 5...",NaN
6,6,Greenwood Park,https://bradforddistrictparks.org/park/greenwo...,"Wilsden Road, Allerton, BD15 9AD","Open 24 hours a day, all year round",53.814044,-1.8366054,0,0,0,...,0,"Basketball court, Childrens play area, Cricket...",Greenwood Park,"Other Sports Facility, Play Space, Playing Field","2BE88DD4-0458-7FED-E063-AAEFA00A0EDD, 2BE88E25...",Greenwood Park,park,42862661.0,"POLYGON ((576722.801 5963482.189, 576665.305 5...",NaN
7,7,Grange Park,https://bradforddistrictparks.org/park/grange-...,"Main Street, Burley-in-Wharfedale, Ilkley, LS2...","Open 24 hours a day, all year round",53.9130668,-1.7492053,0,0,0,...,0,"Childrens play area, Fitness equipment",Grange Park,"Bowling Green, Play Space, Public Park Or Garden","2BE88E23-F4D0-7FED-E063-AAEFA00A0EDD, 2BE88E23...",Grange Park,park,60671740.0,"POLYGON ((582106.481 5974534.031, 582106.473 5...",NaN
8,8,Foxhill Park,https://bradforddistrictparks.org/park/foxhill...,"Fleet Lane, Queensbury, BD13 2JR","Open 24 hours a day, all year round",53.7712639,-1.8547914,0,0,0,...,0,Full size football pitch,Foxhill Park,Playing Field,2BE88E26-0BD1-7FED-E063-AAEFA00A0EDD,Foxhill Park,park,168515340.0,"POLYGON ((575314.442 5958697.058, 575314.649 5...",NaN
14,14,Knowles Park,https://bradforddistrictparks.org/park/knowles...,"Holme Wood, Bradford, BD4 9PP","Open 24 hours a day, all year round",53.7724228,-1.7194417,1,0,1,...,0,"Car parking, Childrens play area, Dog free are...",Knowles Park,"Bowling Green, Play Space, Public Park Or Garden","2BE88DD9-604B-7FED-E063-AAEFA00A0EDD, 2BE88E28...",Knowles Park,park,54444001.0,"POLYGON ((584420.492 5958868.434, 584417.832 5...",NaN
23,23,Seymour Street Recreation Ground,https://bradforddistrictparks.org/park/seymour...,"Upper Seymour Street, \r\nBradford,\r\nBD3 9LJ",NA,None,None,0,0,0,...,0,NA,Seymour Street Recreation Ground,"Other Sports Facility, Play Space, Playing Field","2BE88E27-85A2-7FED-E063-AAEFA00A0EDD, 2BE88E27...",Seymour Park,park,27359839.0,"POLYGON ((583390.488 5961242.250, 583386.479 5...",NaN
26,26,Eccleshill Park,https://bradforddistrictparks.org/park/ecclesh...,"Rimswell Holt, Greengates, BD10 0EY","Open 24 hours a day, all year round",53.8242976,-1.7105699,0,0,0,...,0,"BMX track, Childrens play area, Fitness equipm...",Eccleshill Park,"Play Space, Public Park Or Garden","2BE88E27-B71A-7FED-E063-AAEFA00A0EDD, 2BE88E27...",,wood,"1240758815.0, 1240758816.0","MULTIPOLYGON (((584890.460 5964678.190, 584884...",NaN
28,28,Cross Roads Park,https://bradforddistrictparks.org/park/cross-r...,NA,NA,None,None,0,0,0,...,0,NA,Cross Roads Park,"Bowling Green, Other Sports Facility, Play Spa...","2BE88E23-74A7-7FED-E063-AAEFA00A0EDD, 2BE88E23...",Cross Roads Park,park,1081617151.0,"POLYGON ((570290.516 5965934.824, 570300.733 5...",NaN
40,40,Wibsey Park,https://bradforddistrictparks.org/park/wibsey-...,"Wibsey Park Avenue, Bradford BD6 3QD","Open 24 hours a day, all year round",53.76673410000001,-1.787095700000009,0,0,1,...,0,"BMX track, Bowling green, Childrens play area,...",Wibsey Park,"Bowling Green, Other Sports Facility, Play Spa...","2BE88DD3-BEA9-7FED-E063-AAEFA00A0EDD, 2BE88DE0...",Wibsey Park,"park, wood","200726700.0, 200947589.0, 958222047.0","POLYGON ((579687.387 5958070.287, 579688.126 5...",NaN
49,49,Prince of Wales Park,https://bradforddistrictparks.org/park/prince-...,"Park Drive, Bingley, BD16 3DF","Open 24 hours a day, all year round",53.85672470000001,-1.8258287999999538,0,0,1,...,0,"Childrens play area, Picnic area, Walking routes",Prince of Wales Park,Public Park Or Garden,2BE88E23-BC1A-7FED-E063-AAEFA00A0EDD,Prince of Wales Park,park,180572882.0,"POLYGON ((577329.858 5968401.662, 577351.470 5...",NaN
50,50,Peel Park,https://bradforddistrictparks.org/park/peel-park/,"Cliffe Road, Bradford, BD3 OLT","Open 24 hours a day, all year round",53.80551579999999,-1.7430083000000423,0,0,1,...,0,"5-a-side football pitch, Accessibility route, ...",Peel Park,"Bowling Green, Other Sports Facility, Play Spa...","2BE88DCE-F345-7FED-E063-AAEFA00A0EDD, 2BE88DD2...",Peel Park,"park, scrub, wood","149672964.0, 27413170.0, 730212832.0","POLYGON ((582450.968 5963062.599, 582515.377 5...",NaN
53,53,Lund Park,https://bradforddistrictparks.org/park/lund-park/,"Malsis Road, Keighley, BD21 1JQ","Open 24 hours a day, all year round",53.8603671,-1.9190687000000253,0,0,1,...,0,"BMX track, Bowling green, Childrens play area,...",Lund Park,"Bowling Green, Play Space, Public Park Or Garden","2BE88E23-568E-7FED-E063-AAEFA00A0EDD, 2BE88E23...",Lund Park,park,35836067.0,"POLYGON ((571182.936 5968601.663, 571202.019 5...",NaN
54,54,Littlemoor Park,https://bradforddistrictparks.org/park/littlem...,"Scarlet Heights, BD13","Open 24 hours a day, all year round",53.77008088558352,-1.8339752941650431,0,0,1,...,0,Walking routes,Littlemoor Park,Public Park Or Garden,2BE88E2C-9CC8-7FED-E063-AAEFA00A0EDD,Littlemoor Park,"park, wood","1244205556.0, 1244205561.0, 1244205562.0, 1244...","POLYGON ((577073.515 5958042.041, 577045.861 5...",NaN
55,55,Ladyhill Park,https://bradforddistrictparks.org/park/ladyhil...,"Chapel Lane, Allerton, BD15 7AB","Open 24 hours a day, all year round",53.80225429999999,-1.813534900000036,0,0,0,...,0,"Basketball court, Bowling green, Childrens pla...",Ladyhill Park,"Allotments Or Community Growing Spaces, Bowlin...","2BE88E25-93BA-7FED-E063-AAEFA00A0EDD, 2BE88E25...",Lady Hill Park,park,32198941.0,"POLYGON ((578129.091 5961996.491, 578069.071 5...",NaN
56,56,Horton Park,https://bradforddistrictparks.org/park/horton-...,"Horton Park Avenue, BD7 3EG","Open 24 hours a day, all year round",53.7828131,-1.7747898999999734,1,0,0,...,0,"Bowling green, Car parking, Childrens play are...",Horton Park,"Bowling Green, Other Sports Facility, Play Spa...","2BE88DE6-1D9F-7FED-E063-AAEFA00A0EDD, 2BE88E27...",Horton Park,park,27438406.0,"POLYGON ((580409.379 5959868.882, 580396.525 5...",NaN
59,59,Foster Park,https://bradforddistrictparks.org/park/foster-...,"Foster Park View, Denholme, BD13","Open 24 hours a day, all year round",53.8033033,-1.8933164000000033,0,0,1,...,0,"5-a-side football pitch, Bandstand, Basketball...",Foster Park,"Bowling Green, Other Sports Facility, Play Spa...","2BE88E25-7A7F-7FED-E063-AAEFA00A0EDD, 2BE88E25...",Foster Park,"park, wood","104736445.0, 104742560.0","POLYGON ((573017.239 5961871.246, 573017.083 5...",NaN
60,60,Devonshire Park,https://bradforddistrictparks.org/park/devonsh...,"Vernon Court, Keighley","Open 24 hours a day, all year round",53.8713293,-1.9132191,0,0,1,...,0,"5-a-side football pitch, Childrens play area, ...",Devonshire Park,"Bowling Green, Other Sports Facility, Play Spa...","2BE88DD7-9FFC-7FED-E063-AAEFA00A0EDD, 2BE88E23...",Devonshire Park,park,67563452.0,"POLYGON ((571316.851 5969758.011, 571318.898 5...",NaN
61,61,Crowgill Park,https://bradforddistrictparks.org/park/crowgil...,"Crowgill Road, Shipley, BD18","Open 24 hours a day, all year round",53.8339681,-1.7810047000000395,0,0,0,...,0,"Bowling green, Fitness equipment, Skate park",Crowgill Park,"Bowling Green, Play Space, Public Park Or Garden","2BE88DD7-A00B-7FED-E063-AAEFA00A0EDD, 2BE88E24...",Crowgill Park,park,42760759.0,"POLYGON ((580264.728 5965724.583, 580259.454 5...",NaN
62,62,Cross Roads Park,https://bradforddistrictparks.org/park/cross-r...,"Halifax Road, Cross Roads, Keighley, BD22 9BQ","Open 24 hours a day, all year round",53.8364282,-1.9318984999999884,0,0,0,...,0,"5-a-side football pitch, Basketball court, Bow...",Cross Roads Park,"Bowling Green, Other Sports Facility, Play Spa...","2BE88E23-74A7-7FED-E063-AAEFA00A0EDD, 2BE88E23...",Cross Roads Park,park,1081617151.0,"POLYGON ((570290.516 5965934.824, 570300.733 5...",NaN
65,65,Brackenhill Park,https://bradforddistrictparks.org/park/bracken...,"Brackenhill Drive, BD7 4RS","Open 24 hours a day, all year round",53.7803099,-1.7970755,1,0,0,...,0,"Bowling green, Car parking, Childrens play are...",Brackenhill Park,"Bowling Green, Other Sports Facility, Play Spa...","2BE88E27-4A62-7FED-E063-AAEFA00A0EDD, 2BE88E27...",Brackenhill Park,park,75665034.0,"POLYGON ((579197.415 5959769.654, 579222.183 5...",NaN
66,66,Lister Park,https://bradforddistrictparks.org/park/lister-...,"North Park Road, Bradford, BD9 4NS","Open 24 hours a day, all year round",53.813188,-1.7721311999999898,1,0,1,...,0,"Bandstand, Boating lake, Café, Car parking, Fi...",Lister Park,"Bowling Green, Other Sports Facility, Play Spa...","2BE88E26-C569-7FED-E063-AAEFA00A0EDD, 2BE88E26...",Lister Park,"park, scrub, wood","1185655920.0, 1185655921.0, 28071166.0","POLYGON ((580901.926 5963183.155, 580845.820 5...",NaN
69,69,Bradford Moor Park,https://bradforddistrictparks.org/park/bradfor...,"Killinghall Road, BD3 7JD","Open 24 hours a day, all year round",53.7998973,-1.719939,0,0,1,...,0,"5-a-side football pitch, Basketball court, Bow...",Bradford Moor Park,"Bowling Green, Other Sports Facility, Play Spa...","2BE88E27-7F48-7FED-E063-AAEFA00A0EDD, 2BE88E27...",Bradford Moor Park,park,142734326.0,"POLYGON ((584163.994 5962203.377, 584144.557 5...",NaN
16,16,Parkside Park,https://bradforddistrictparks.org/park/parksid...,"Parkside Road,\r\nWest Bowling,\r\nBradford,\r...",NA,None,None,0,0,0,...,0,NA,,"Other Sports Facility, Play Space, Public Park...","2BE88DCF-1DED-7FED-E063-AAEFA00A0EDD, 2BE88DD0...",Parkside Park,park,27550933.0,"POLYGON ((582274.358 5959039.909, 582274.333 5...",NaN
34,34,Judy Woods,https://bradforddistrictparks.org/park/judy-wo...,"Station Road, Wyke, Bradford, BD12 8LA and Mea...","Open 24 hours a day, all year round",53.7370778,-1.7795027,0,1,1,...,0,"Cycle route, Horse route, Nature reserve, Publ...",,,,Judy Woods,wood,"200685812.0, 200685817.0","POLYGON ((580436.864 5955827.528, 580484.574 5...",NaN
35,35,Griff Wood,https://bradforddistrictparks.org/park/griff-w...,"Grey Scar Road Oakworth, BD22 0SA","Open 24 hours a day, all year round",53.8464876,-1.9623325,0,0,1,...,0,Walking routes,,,,Griff Wood,wood,128980978.0,"POLYGON ((567872.618 5967184.199, 567959.632 5...",NaN
46,46,Silsden Park,https://bradforddistrictparks.org/park/silsden...,"Bolton Road, Silsden, Keighley, BD20 0JY","Open 24 hours a day, all year round",53.9141861,-1.9345493,0,0,0,...,0,"Basketball court, Bowling green, Childrens pla...",,"Bowling Green, Play Space, Playing Field, Tenn...","2BE88DD7-A096-7FED-E063-AAEFA00A0EDD, 2BE88E22...",Silsden Park,"park, wood","558459227.0, 558731448.0, 558731449.0, 5587314...","POLYGON ((569871.559 5974503.101, 569865.277 5...",NaN
47,47,Shipley Central Park,https://bradforddistrictparks.org/park/shipley...,"Westcliffe Road, Shipley, BD18 3DX","Open 24 hours a day, all year round",53.831391009229094,-1.7821336983979563,0,0,0,...,0,"Childrens play area, Fitness equipment, Picnic...",,"Play Space, Public Park Or Garden","2BE88DD8-907D-7FED-E063-AAEFA00A0EDD, 2BE88E26...",Shipley Central Park,park,42444511.0,"POLYGON ((580101.711 5965506.037, 580108.886 5...",NaN
9,9,"Riverside Gardens, Ilkley",https://bradforddistrictparks.org/park/riversi...,"Bridge Lane, Ilkley LS29 9EU","Open 24 hours a day, all year round",53.9277309,-1.8260355,1,1,1,...,0,"Accessibility route, Car parking, Childrens pl...","Ilkley Parish Church, Riverside Gardens","Play Space, Public Park Or Garden, Religious ...","2BE88E23-0723-7FED-E063-AAEFA00A0EDD, 2BE88E2...",Riverside Gardens,"meadow, park","1390680287.0, 4536859.0, 4985992.0, 4985993.0",POINT (577084.411 5976119.358),178.0
37,37,Crabtree Ghyll,https://bradforddistrictparks.org/park/crabtre...,LS29 0AU,"Open 24 hours a day, all year round",53.93574441520943,-1.8309709154052598,0,0,1,...,0,Walking routes,,,,"Coppy Wood / Stubham Wood, Crabtree Gill, Paw...","meadow, wood","103535745.0, 275868979.0, 275868994.0, 2758695...",POINT (576745.652 5977005.523),657.0
38,38,Buck Wood,https://bradforddistrictparks.org/park/buck-wood/,"Ainsbury Avenue, Thackley, BD10 0TL","Open 24 hours a day, all year round",53.8496793,-1.7245705,0,0,1,...,0,"Accessibility route, BMX track, Cycle route, N...",,"Other Sports Facility, Playing Field","2BE88E2C-9A60-7FED-E063-AAEFA00A0EDD, 2BE88F...","Buck Wood, Dawson Wood","forest, scrub, wood","1265680817.0, 1265681507.0, 1265682095.0, 126...",POINT (583902.626 5967551.234),565.0
41,41,"West Park, Girlington",https://bradforddistrictparks.org/park/west-pa...,"West Park Road, Girlington, BD8 9SJ","Open 24 hours a day, all year round",53.8008653,-1.7918983,0,0,0,...,0,"Childrens play area, Multi use games area, Ska...",Girlington Recreation Ground,"Bowling Green, Play Space, Playing Field","2BE88DD7-A036-7FED-E063-AAEFA00A0EDD, 2BE88E27...",West Park,park,175665224.0,POINT (579566.195 5962043.170),68.0
42,42,"Victoria Park, Oakenshaw",https://bradforddistrictparks.org/park/victori...,"Cleckheaton Road, Oakenshaw, BD12 7AT","Open 24 hours a day, all year round",53.74890440000001,-1.7496512000000166,1,0,0,...,0,"5-a-side football pitch, Bowling green, Car pa...",Victoria Park,"Bowling Green, Play Space, Public Park Or Garden","2BE88DD7-A087-7FED-E063-AAEFA00A0EDD, 2BE88DD...","Low Moor Banks, Victoria Park","park, wood","1351673958.0, 168072361.0, 481123820.0, 898111...",POINT (582450.259 5956310.784),79.0
43,43,"Victoria Park, Keighley",https://bradforddistrictparks.org/park/victori...,"Hard Ings Road, Keighley, BD21","Open 24 hours a day, all year round",53.8729222,-1.8984358000000157,0,0,1,...,0,"Basketball court, Childrens play area, Fitness...",Victoria Park,"Other Sports Facility, Play Space, Public Park...","2BE88E23-8755-7FED-E063-AAEFA00A0EDD, 2BE88E23...",Victoria Park,park,42147678.0,POINT (572425.409 5969945.452),231.0
44,44,"Victoria Park, Clayton",https://bradforddistrictparks.org/park/victori...,"Clayton Lane, Clayton, Bradford, BD14","Open 24 hours a day, all year round",53.7819452,-1.821450499999969,0,0,0,...,0,"Basketball court, Bowling green, Childrens pla...",Victoria Park,"Bowling Green, Other Sports Facility, Play Spa...","2BE88E25-AF7A-7FED-E063-AAEFA00A0EDD, 2BE88E25...",Victoria Park,park,72661176.0,POINT (577654.895 5959905.603),379.0
48,48,Roberts Park,https://bradforddistrictparks.org/park/roberts...,"Higher Coach Road, Saltaire, Baildon, Shipley,...","Open 24 hours a day, all year round",53.8409379,-1.791769199999976,1,1,1,...,0,"Accessibility route, Bandstand, Café, Car park...","Roberts Park, Saltaire Cricket Ground","Play Space, Playing Field, Public Park Or Garden","2BE88DE1-6FE6-7FED-E063-AAEFA00A0EDD, 2BE88E24...",Roberts Park,park,10072074.0,POINT (579498.804 5966501.378),131.0
51,51,Myrtle Park,https://bradforddistrictparks.org/park/myrtle-...,"Myrtle Grove, Bingley, BD16 2LQ","Open 24 hours a day, all year round",53.8467826,-1.8396408999999494,0,0,0,...,0,"Aviary, Bowling green, Café, Childrens play ar...","Myrtle Park, Princess Hall","Bowling Green, Other Sports Facility, Play Spa...","2BE88DD8-A640-7FED-E063-AAEFA00A0EDD, 2BE88DDE...",Myrtle Park,"park, wood","1062206248.0, 181008272.0",POINT (576338.455 5967099.034),97.0
52,52,Menston Park,https://bradforddistrictparks.org/park/menston...,"Bingley Road, Menston, Ilkley, LS29 6GA","Open 24 hours a day, all year round",53.8871549,-1.7347562,0,0,0,...,0,"Childrens play area, Skate park, Tennis court",,"Play Space, Playing Field, Tennis Court","2BE88E24-376F-7FED-E063-AAEFA00A0EDD, 2BE88E24...",Menston Recreation Ground,park,25741364.0,POINT (583158.234 5971708.389),283.0
57,57,Holden Park (Oakworth Park),https://bradforddistrictparks.org/park/holden-...,"Colne Road/Keighley Road, Oakworth, Keighley, ...","Open 24 hours a day, all year round",53.84779899999999,-1.9510887999999795,0,0,0,...,0,"Bowling green, Childrens play area, Multi use ...",Holden Park,"Bowling Green, Play Space, Public Park Or Gard...","2BE88E23-6AE1-7FED-E063-AAEFA00A0EDD, 2BE88E23...","Holden Park, Near High Field","meadow, park, wood","14356339.0, 145260876.0, 178838789.0",POINT (569005.039 5967097.962),215.0
58,58,Harold Park,https://bradforddistrictparks.org/park/harold-...,"Low Moor, Bradford, BD12 0EW","Open 24 hours a day, all year round",53.7569903,-1.7742977,1,0,1,...,0,"5-a-side football pitch, Angling, Basketball c...","Harold Park, Horsfall Playing Fields","Bowling Green, Other Sports Facility, Play Spa...","2BE88E28-986A-7FED-E063-AAEFA00A0EDD, 2BE88E28...",Harold Park,"park, scrub, wood","200688241.0, 201079212.0, 201079214.0",POINT (580809.578 5957182.003),525.0
63,63,Cliffe Castle Museum & Park,https://bradforddistrictparks.org/park/cliffe-...,"Spring Gardens Lane, Keighley, BD20 6LH","Open 24 hours a day, all year round",53.8750763,-1.9138292000000092,1,0,1,...,0,"Aviary, Bandstand, Café, Car parking, Children...",Cliffe Castle Park,"Play Space, Public Park Or Garden","2BE88DDA-1EDD-7FED-E063-AAEFA00A0EDD, 2BE88DE4...","Cliffe Castle Park, Moorhouse Wood","park, wood","113071583.0, 113071620.0",POINT (571409.695 5970169.492),105.0
64,64,"Central Park, Haworth",https://bradforddistrictparks.org/park/central...,"Rawdon Road, Keighley, BD22 8QE","Open 24 hours a day, all year round",53.82926929999999,-1.9524292999999489,0,0,0,...,0,"Bowling green, Childrens play area, Public scu...","Central Park, Playground","Bowling Green, Play Space, Public Park Or Garden","2BE88E25-309C-7FED-E063-AAEFA00A0EDD, 2BE88E25...",Central Park,park,129312804.0,POINT (568947.287 5965035.196),331.0
67,67,Middleton Woods,https://bradforddistrictparks.org/park/middlet...,"Denton Road, LS29 8EW","Open 24 hours a day, all year round",53.934798993183,-1.7972921622379,0,0,1,...,0,"Nature reserve, Walking routes, Wildflower area",,,,West Park Wood,"meadow, wood","120556161.0, 120556164.0, 120556843.0, 4938240...",POINT (578958.317 5976937.338),639.0
68,68,Northcliffe Park,https://bradforddistrictparks.org/park/northcl...,"Bradford Road, BD18 3BX","Open 24 hours a day, all year round",53.8274937,-1.7826430000000073,0,0,1,...,1,"Bowling green, Childrens play area, Fitness eq...","Heaton Graveyard, Norman Rae Playing Fields, ...","Allotments Or Community Growing Spaces, Bowli...","0A0C1723-E2A4-4FA1-B127-F73A7954FB7B, 2BE88DD...","Dungeon Wood, Heaton Woods, Northcliffe Park,...","forest, meadow, park, wood, wood,","155329517.0, 155329519.0, 42446869.0, 4244687...",POINT (580124.918 5965015.977),0.0

In [14]:
#### NEED TO BUG SOLVE ONLY SAVING POLYGON_3 as points. 
bd_parks_polygon_3.explore()

In [15]:

# get boundsing box of 400m arround each park to calcualte network connectivity 
bradford_parks_gdf =bradford_parks_gdf.to_crs('EPSG:2770')
# conver back to 4326 after buffer for bbox crs
cols =bradford_parks_gdf.buffer(400).to_crs('EPSG:4326').bounds.add_prefix('400m_bounding_').columns
bradford_parks_gdf[cols]= bradford_parks_gdf.buffer(400).to_crs('EPSG:4326').bounds.add_prefix('400m_bounding_')
bradford_parks_gdf

,index,Park Name,Park URL,Location,Opening Hours,Latitude,Longitude,Car parking,River,Walking routes,...,OS ID,Name (OSM),Type (OSM),OSM ID,geometry,index_right,400m_bounding_minx,400m_bounding_miny,400m_bounding_maxx,400m_bounding_maxy
5,5,Russell Hall Park,https://bradforddistrictparks.org/park/russell...,"Russell Hall Ave, Queensbury, BD13 2AL","Open 24 hours a day, all year round",53.7652724,-1.8488896,0,0,0,...,"2BE88E26-152D-7FED-E063-AAEFA00A0EDD, 2BE88E26...",Russell Hall Park,park,200908882.0,"POLYGON ((8448768.006 6998427.250, 8448764.841...",NaN,-1.855965,53.760832,-1.841952,53.769118
6,6,Greenwood Park,https://bradforddistrictparks.org/park/greenwo...,"Wilsden Road, Allerton, BD15 9AD","Open 24 hours a day, all year round",53.814044,-1.8366054,0,0,0,...,"2BE88DD4-0458-7FED-E063-AAEFA00A0EDD, 2BE88E25...",Greenwood Park,park,42862661.0,"POLYGON ((8443867.032 7001767.852, 8443823.797...",NaN,-1.841258,53.810252,-1.827201,53.818701
7,7,Grange Park,https://bradforddistrictparks.org/park/grange-...,"Main Street, Burley-in-Wharfedale, Ilkley, LS2...","Open 24 hours a day, all year round",53.9130668,-1.7492053,0,0,0,...,"2BE88E23-F4D0-7FED-E063-AAEFA00A0EDD, 2BE88E23...",Grange Park,park,60671740.0,"POLYGON ((8435581.160 7011893.989, 8435581.464...",NaN,-1.756059,53.909031,-1.742106,53.917074
8,8,Foxhill Park,https://bradforddistrictparks.org/park/foxhill...,"Fleet Lane, Queensbury, BD13 2JR","Open 24 hours a day, all year round",53.7712639,-1.8547914,0,0,0,...,2BE88E26-0BD1-7FED-E063-AAEFA00A0EDD,Foxhill Park,park,168515340.0,"POLYGON ((8447864.339 6998278.046, 8447863.869...",NaN,-1.862943,53.766891,-1.847155,53.775736
14,14,Knowles Park,https://bradforddistrictparks.org/park/knowles...,"Holme Wood, Bradford, BD4 9PP","Open 24 hours a day, all year round",53.7724228,-1.7194417,1,0,1,...,"2BE88DD9-604B-7FED-E063-AAEFA00A0EDD, 2BE88E28...",Knowles Park,park,54444001.0,"POLYGON ((8451751.492 7007151.197, 8451752.392...",NaN,-1.728002,53.767632,-1.710852,53.777120
23,23,Seymour Street Recreation Ground,https://bradforddistrictparks.org/park/seymour...,"Upper Seymour Street, \r\nBradford,\r\nBD3 9LJ",NA,None,None,0,0,0,...,"2BE88E27-85A2-7FED-E063-AAEFA00A0EDD, 2BE88E27...",Seymour Park,park,27359839.0,"POLYGON ((8448999.693 7007213.359, 8449028.205...",NaN,-1.741298,53.789419,-1.727552,53.797631
26,26,Eccleshill Park,https://bradforddistrictparks.org/park/ecclesh...,"Rimswell Holt, Greengates, BD10 0EY","Open 24 hours a day, all year round",53.8242976,-1.7105699,0,0,0,...,"2BE88E27-B71A-7FED-E063-AAEFA00A0EDD, 2BE88E27...",,wood,"1240758815.0, 1240758816.0","MULTIPOLYGON (((8446348.162 7010193.080, 84463...",NaN,-1.717435,53.819734,-1.703269,53.828980
28,28,Cross Roads Park,https://bradforddistrictparks.org/park/cross-r...,NA,NA,None,None,0,0,0,...,"2BE88E23-74A7-7FED-E063-AAEFA00A0EDD, 2BE88E23...",Cross Roads Park,park,1081617151.0,"POLYGON ((8438634.851 6996641.521, 8438666.735...",NaN,-1.939164,53.831962,-1.925510,53.840558
40,40,Wibsey Park,https://bradforddistrictparks.org/park/wibsey-...,"Wibsey Park Avenue, Bradford BD6 3QD","Open 24 hours a day, all year round",53.76673410000001,-1.787095700000009,0,0,1,...,"2BE88DD3-BEA9-7FED-E063-AAEFA00A0EDD, 2BE88DE0...",Wibsey Park,"park, wood","200726700.0, 200947589.0, 958222047.0","POLYGON ((8450415.405 7002223.882, 8450410.844...",NaN,-1.796840,53.761323,-1.777691,53.771574
49,49,Prince of Wales Park,https://bradforddistrictparks.org/park/prince-...,"Park Drive, Bingley, BD16 3DF","Open 24 hours a day, all year round",53.85672470000001,-1.8258287999999538,0,0,1,...,2BE88E23-BC1A-7FED-E063-AAEFA00A0EDD,Prince of Wales Park,park,180572882.0,"POLYGON ((8439382.271 7004544.312, 8439566.401...",NaN,-1.834680,53.852313,-1.818216,53.862332
50,50,Peel Park,https://bradforddistrictparks.org/park/peel-park/,"Cliffe Road, Bradford, BD3 OLT","Open 24 hours a day, all year round",53.80551579999999,-1.7430083000000423,0,0,1,...,"2BE88DCE-F345-7FED-E063-AAEFA00A0EDD, 2BE88DD2...",Peel Park,"park, scrub, wood","149672964.0, 27413170.0, 730212832.0","POLYGON ((8446822.550 7007116.317, 8446812.686...",NaN,-1.756202,53.802189,-1.728245,53.814397
53,53,Lund Park,https://bradforddistrictparks.org/park/lund-park/,"Malsis Road, Keighley, BD21 1JQ","Open 24 hours a day, all year round",53.8603671,-1.9190687000000253,0,0,1,...,"2BE88E23-568E-7FED-E063-AAEFA00A0EDD, 2BE88E23...",Lund Park,park,35836067.0,"POLYGON ((8436453.389 6998690.485, 8436478.075...",NaN,-1.927546,53.855451,-1.910819,53.865115
54,54,Littlemoor Park,https://bradforddistrictparks.org/park/littlem...,"Scarlet Heights, BD13","Open 24 hours a day, all year round",53.77008088558352,-1.8339752941650431,0,0,1,...,2BE88E2C-9CC8-7FED-E063-AAEFA00A0EDD,Littlemoor Park,"park, wood","1244205556.0, 1244205561.0, 1244205562.0, 1244...","POLYGON ((8449279.657 6999686.182, 8449275.729...",NaN,-1.843588,53.760838,-1.823604,53.773217
55,55,Ladyhill Park,https://bradforddistrictparks.org/park/ladyhil...,"Chapel Lane, Allerton, BD15 7AB","Open 24 hours a day, all year round",53.80225429999999,-1.813534900000036,0,0,0,...,"2BE88E25-93BA-7FED-E063-AAEFA00A0EDD, 2BE88E25...",Lady Hill Park,park,32198941.0,"POLYGON ((8445928.594 7002465.646, 8445898.283...",NaN,-1.820699,53.796912,-1.805848,53.806825
56,56,Horton Park,https://bradforddistrictparks.org/park/horton-...,"Horton Park Avenue, BD7 3EG","Open 24 hours a day, all year round",53.7828131,-1.7747898999999734,1,0,0,...,"2BE88DE6-1D9F-7FED-E063-AAEFA00A0EDD, 2BE88E27...",Horton Park,park,27438406.0,"POLYGON ((8448999.205 7003721.872, 8448982.237...",NaN,-1.785537,53.777193,-1.765063,53.788065
59,59,Foster Park,https://bradforddistrictparks.org/park/foster-...,"Foster Park View, Denholme, BD13","Open 24 hours a day, all year round",53.8033033,-1.8933164000000033,0,0,1,...,"2BE88E25-7A7F-7FED-E063-AAEFA00A0EDD, 2BE88E25...",Foster Park,"park, wood","104736445.0, 104742560.0","POLYGON ((8443775.367 6997470.001, 8443766.471...",NaN,-1.899911,53.796910,-1.884676,53.806483
60,60,Devonshire Park,https://bradforddistrictparks.org/park/devonsh...,"Vernon Court, Keighley","Open 24 hours a day, all year round",53.8713293,-1.9132191,0,0,1,...,"2BE88DD7-9FFC-7FED-E063-AAEFA00A0EDD, 2BE88E23...",Devonshire Park,park,67563452.0,"POLYGON ((8435394.855 6999334.390, 8435319.041...",NaN,-1.921208,53.867020,-1.904902,53.875834
61,61,Crowgill Park,https://bradforddistrictparks.org/park/crowgil...,"Crowgill Road, Shipley, BD18","Open 24 hours a day, all year round",53.8339681,-1.7810047000000395,0,0,0,...,"2BE88DD7-A00B-7FED-E063-AAEFA00A0EDD, 2BE88E24...",Crowgill Park,park,42760759.0,"POLYGON ((8443276.610 7006189.109, 8443290.741...",NaN,-1.787462,53.830245,-1.774129,53.838363
62,62,Cross Roads Park,https://bradforddistrictparks.org/park/cross-r...,"Halifax Road, Cross Roads, Keighley, BD22 9BQ","Open 24 hours a day, all year round",53.8364282,-1.9318984999999884,0,0,0,...,"2BE88E23-74A7-7FED-E063-AAEFA00A0EDD, 2BE88E23...",Cross Roads Park,park,1081617151.0,"POLYGON ((8438634.851 6996641.521, 8438666.735...",NaN,-1.939164,53.831962,-1.925510,53.840558
65,65,Brackenhill Park,https://bradforddistrictparks.org/park/bracken...,"Brackenhill Drive, BD7 4RS","Open 24 hours a day, all year round",53.7803099,-1.7970755,1,0,0,...,"2BE88E27-4A62-7FED-E063-AAEFA00A0EDD, 2BE88E27...",Brackenhill Park,park,75665034.0,"POLYGON ((8448555.643 7002506.815, 8448530.007...",NaN,-1.803945,53.775658,-1.780793,53.786146
66,66,Lister Park,https://bradforddistrictparks.org/park/lister-...,"North Park Road, Bradford, BD9 4NS","Open 24 hours a day, all year round",53.813188,-1.7721311999999898,1,0,1,...,"2BE88E26-C569-7FED-E063-AAEFA00A0EDD, 2BE88E26...",Lister Park,"park, scrub, wood","1185655920.0, 1185655921.0, 28071166.0","POLYGON ((8446016.278 7005673.240, 8445972.598...",NaN,-1.784993,53.805980,-1.761937,53.818933
69,69,Bradford Moor Park,https://bradforddistrictparks.org/park/bradfor...,"Killinghall Road, BD3 7JD","Open 24 hours a day, all year round",53.7998973,-1.719939,0,0,1,...,"2BE88E27-7F48-7FED-E063-AAEFA00A0EDD, 2BE88E27...",Bradford Moor Park,park,142734326.0,"POLYGON ((8448415.651 7008388.711, 8448370.206...",NaN,-1.728026,53.795294,-1.711971,53.805896
16,16,Parkside Park,https://bradforddistrictparks.org/park/parksid...,"Parkside Road,\r\nWest Bowling,\r\nBradford,\r...",NA,None,None,0,0,0,...,"2BE88DCF-1DED-7FED-E063-AAEFA00A0EDD, 2BE88DD0...",Parkside Park,park,27550933.0,"POLYGON ((8450630.252 7005154.491, 8450630.242...",NaN,-1.757801,53.770081,-1.744593,53.778600
34,34,Judy Woods,https://bradforddistrictparks.org/park/judy-wo...,"Station Road, Wyke, Bradford, BD12 8LA and Mea...","Open 24 hours a day, all year round",53.7370778,-1.7795027,0,1,1,...,,Judy Woods,wood,"200685812.0, 200685817.0","POLYGON ((8452915.286 7001949.772, 8452988.714...",NaN,-1.807384,53.733175,-1.771591,53.758502
35,35,Griff Wood,https://bradforddistrictparks.org/park/griff-w...,"Grey Scar Road Oakworth, BD22 0SA","Open 24 hours a day, all year round",53.8464876,-1.9623325,0,0,1,...,,Griff Wood,wood,128980978.0,"POLYGON ((8436351.774 6994859.339, 8436543.138...",NaN,-1.973970,53.843922,-1.957830,53.852764
46,46,Silsden Park,https://bradforddistrictparks.org/park/silsden...,"Bolton Road, Silsden, Keighley, BD20 0JY","Open 24 hours a day, all year round",53.9141861,-1.9345493,0,0,0,...,"2BE88DD7-A096-7FED-E063-AAEFA00A0EDD, 2BE88E22...",Silsden Park,"park, wood","558459227.0, 558731448.0, 558731449.0, 5587314...","POLYGON ((8430162.713 7000047.772, 8430158.147...",NaN,-1.942362,53.909969,-1.925413,53.919075
47,47,Shipley Central Park,https://bradforddistrictparks.org/park/shipley...,"Westcliffe Road, Shipley, BD18 3DX","Open 24 hours a day, all year round",53.831391009229094,-1.7821336983979563,0,0,0,...,"2BE88DD8-907D-7FED-E063-AAEFA00A0EDD, 2BE88E26...",Shipley Central Park,park,42444511.0,"POLYGON ((8443415.233 7005934.247, 8443418.060...",NaN,-1.788569,53.826992,-1.775328,53.835685
9,9,"Riverside Gardens, Ilkley",https://bradforddistrictparks.org/park/riversi...,"Bridge Lane, Ilkley LS29 9EU","Open 24 hours a day, all year round",53.9277309,-1.8260355,1,1,1,...,"2BE88E23-0723-7FED-E063-AAEFA00A0EDD, 2BE88E2...",Riverside Gardens,"meadow, park","1390680287.0, 4536859.0, 4985992.0, 4985993.0",POINT (8431810.485 7007743.790),178.0,-1.831732,53.924363,-1.820294,53.931114
37,37,Crabtree Ghyll,https://bradforddistrictparks.org/park/crabtre...,LS29 0AU,"Open 24 hours a day, all year round",53.93574441520943,-1.8309709154052598,0,0,1,...,,"Coppy Wood / Stubham Wood, Crabtree Gill, Paw...","meadow, wood","103535745.0, 275868979.0, 275868994.0, 2758695...",POINT (8430802.494 7007810.869),657.0,-1.836669,53.932377,-1.825229,53.939127
38,38,Buck Wood,https://bradforddistrictparks.org/park/buck-wood/,"Ainsbury Avenue, Thackley, BD10 0TL","Open 24 hours a day, all year round",53.8496793,-1.7245705,0,0,1,...,"2BE88E2C-9A60-7FED-E063-AAEFA00A0EDD, 2BE88F...","Buck Wood, Dawson Wood","forest, scrub, wood","1265680817.0, 1265681507.0, 1265682095.0, 126...",POINT (8443131.687 7010518.586),565.0,-1.730260,53.846309,-1.718837,53.853064
41,41,"West Park, Girlington",https://bradforddistrictparks.org/park/west-pa...,"West Park Road, Girlington, BD8 9SJ","Open 24 hours a day, all year round",53.8008653,-1.7918983,0,0,0,...,"2BE88DD7-A036-7FED-E063-AAEFA00A0EDD, 2BE88E27...",West Park,park,175665224.0,POINT (8446523.139 7003875.054),68.0,-1.797583,53.797494,-1.786169,53.804251
42,42,"Victoria Park, Oakenshaw",https://bradforddistrictparks.org/park/victori...,"Cleckheaton Road, Oakenshaw, BD12 7AT","Open 24 hours a day, all year round",53.74890440000001,-1.7496512000000166,1,0,0,...,"2BE88DD7-A087-7FED-E063-AAEFA00A0EDD, 2BE88DD...","Low Moor Banks, Victoria Park","park, wood","1351673958.0, 168072361.0, 481123820.0, 898111...",POINT (8453344.634 7004109.469),79.0,-1.755331,53.745532,-1.743927,53.752291
43,43,"Victoria Park, Keighley",https://bradforddistrictparks.org/park/victori...,"Hard Ings Road, Keighley, BD21","Open 24 hours a day, all year round",53.8729222,-1.8984358000000157,0,0,1,...,"2BE88E23-8755-7FED-E063-AAEFA00A0EDD, 2BE88E23...",Victoria Park,park,42147678.0,POINT (8435706.830 7000489.709),231.0,-1.904127,53.869553,-1.892700,53.876306
44,44,"Victoria Park, Clayton",https://bradforddistrictparks.org/park/victori...,"Clayton Lane, Clayton, Bradford, BD14","Open 24 hours a day, all year round",53.7819452,-1.821450499999969,0,0,0,...,"2BE88E25-AF7A-7FED-E063-AAEFA00A0EDD, 2BE88E25...",Victoria Park,park,72661176.0,POINT (8447737.867 7001077.001),379.0,-1.827134,53.778574,-1.815723,53.785331
48,48,Roberts Park,https://bradforddistrictparks.org/park/roberts...,"Higher Coach Road, Saltaire, Baildon, Shipley,...","Open 24 hours a day, all year round",53.8409379,-1.791769199999976,1,1,1,...,"2BE88DE1-6FE6-7FED-E063-AAEFA00A0EDD, 2BE88E24...",Roberts Park,park,10072074.0,POINT (8442184.797 7005794.752),131.0,-1.797458,53.837568,-1.786036,53.844323
51,51,Myrtle Park,https://bradforddistrictparks.org/park/myrtle-...,"Myrtle Grove, Bingley, BD16 2LQ","Open 24 hours a day, all year round",53.8467826,-1.8396408999999494,0,0,0,...,"2BE88DD8-A640-7FED-E063-AAEFA00A0EDD, 2BE88DDE...",Myrtle Park,"park, wood","1062206248.0, 181008272.0",POINT (8440200.162 7003006.080),97.0,-1.845330,53.843413,-1.833907,53.850167
52,52,Menston Park,https://bradforddistrictparks.org/park/menston...,"Bingley Road, Menston, Ilkley, LS29 6GA","Open 24 hours a day, all year round",53.8871549,-1.7347562,0,0,0,...,"2BE88E24-376F-7FED-E063-AAEFA00A0EDD, 2BE88E24...",Menston Recreation Ground,park,25741364.0,POINT (8438781.762 7011651.546),283.0,-1.740449,53.883786,-1.729019,53.890539
57,57,Holden Park (Oakworth Park),https://bradforddistrictparks.org/park/holden-...,"Colne Road/Keighley Road, Oakworth, Keighley, ...","Open 24 hours a day, all year round",53.84779899999999,-1.9510887999999795,0,0,0,...,"2BE88E23-6AE1-7FED-E063-AAEFA00A0EDD, 2BE88E23...","Holden Park, Near High Field","meadow, park, wood","14356339.0, 145260876.0, 178838789.0",POINT (8436938.669 6995915.927),215.0,-1.956778,53.844429,-1.945355,53.851184
58,58,Harold Park,https://bradforddistrictparks.org/park/harold-...,"Low Moor, Bradford, BD12 0EW","Open 24 hours a day, all year round",53.7569903,-1.7742977,1,0,1,...,"2BE88E28-986A-7FED-E063-AAEFA00A0EDD, 2BE88E28...",Harold Park,"park, scrub, wood","200688241.0, 201079212.0, 201079214.0",POINT (8451772.882 7002912.557),525.0,-1.779978,53.753618,-1.768573,53.760377
63,63,Cliffe Castle Museum & Park,https://bradforddistrictparks.org/park/cliffe-...,"Spring Gardens Lane, Keighley, BD20 6LH","Open 24 hours a day, all year round",53.8750763,-1.9138292000000092,1,0,1,...,"2BE88DDA-1EDD-7FED-E063-AAEFA00A0EDD, 2BE88DE4...","Cliffe Castle Park, Moorhouse Wood","park, wood","113071583.0, 113071620.0",POINT (8435038.269 6999607.233),105.0,-1.919521,53.871707,-1.908093,53.878460
64,64,"Central Park, Haworth",https://bradforddistrictparks.org/park/central...,"Rawdon Road, Keighley, BD22 8QE","Open 24 hours a day, all year round",53.82926929999999,-1.9524292999999489,0,0,0,...,"2BE88E25-309C-7FED-E063-AAEFA00A0EDD, 2BE88E25...",Central Park,park,129312804.0,POINT (8438907.303 6994942.918),331.0,-1.958117,53.825899,-1.946698,53.832654
67,67,Middleton Woods,https://bradforddistrictparks.org/park/middlet...,"Denton Road, LS29 8EW","Open 24 hours a day, all year round",53.934798993183,-1.7972921622379,0,0,1,...,,West Park Wood,"meadow, wood","120556161.0, 120556164.0, 120556843.0, 4938240...",POINT (8431854.184 7009920.568),639.0,-1.802990,53.931431,-1.791550,53.938182
68,68,Northcliffe Park,https://bradforddistrictparks.org/park/northcl...,"Bradford Road, BD18 3BX","Open 24 hours a day, all year round",53.8274937,-1.7826430000000073,0,0,1,...,"0A0C1723-E2A4-4FA1-B127-F73A7954FB7B, 2BE88DD...","Dungeon Wood, Heaton Woods, Northcliffe Park,...","forest, meadow, park, wood, wood,","155329517.0, 155329519.0, 42446869.0, 4244687...",POINT (8443899.172 7005738.465),0.0,-1.788330,53.824123,-1.776911,53.830879

In [22]:
bradford_parks_gdf.to_file("Data/bradford_parks_geom.geojson", driver="GeoJSON")

In [16]:
import osmnx as ox

In [17]:
# G = ox.graph_from_bbox(bradford_parks_gdf.iloc[0]['400m_bounding_maxy'],
#                         bradford_parks_gdf.iloc[0]['400m_bounding_miny'],
#                         bradford_parks_gdf.iloc[0]['400m_bounding_maxx'],
#                         bradford_parks_gdf.iloc[0]['400m_bounding_minx'],
#                         network_type='walk')

# # Calculate the number of corners (nodes with degree 3 or more)
# corners = [node for node, degree in dict(G.degree()).items() if degree >= 3]
# num_corners = len(corners)

# # Calculate the connectiveness (average node degree)
# avg_node_degree = sum(dict(G.degree()).values()) / len(G.nodes)

# print(f"Number of corners: {num_corners}")
# print(f"Connectiveness (average node degree): {avg_node_degree:.2f}")


# # Convert the network into a GeoDataFrame
# gdf_nodes, gdf_edges = ox.graph_to_gdfs(G)

# g

In [19]:
# calculate n corners and connectedness of each network arround each park in the gdf 
bradford_parks_gdf['avg_node_degree_400m_network']=''
bradford_parks_gdf['n_corners_400m_nework']=''
for i in range(0,bradford_parks_gdf.shape[0]):  
    bbox=(
        bradford_parks_gdf.iloc[i]['400m_bounding_maxy'],
        bradford_parks_gdf.iloc[i]['400m_bounding_miny'],
        bradford_parks_gdf.iloc[i]['400m_bounding_maxx'],
        bradford_parks_gdf.iloc[i]['400m_bounding_minx']
        )  
    G = ox.graph_from_bbox(bbox=bbox,
                            network_type='walk')

    # Calculate the number of corners (nodes with degree 3 or more)
    corners = [node for node, degree in dict(G.degree()).items() if degree >= 3]
    num_corners = len(corners)

    # Calculate the connectiveness (average node degree)
    avg_node_degree = sum(dict(G.degree()).values()) / len(G.nodes)
    
    # bradford_parks_gdf.loc[bradford_parks_gdf.index[i], 'avg_node_degree_400m_network'] = avg_node_degree.astype(float)
    bradford_parks_gdf.loc[bradford_parks_gdf.index[i], 'avg_node_degree_400m_network'] = avg_node_degree
    bradford_parks_gdf.loc[bradford_parks_gdf.index[i], 'n_corners_400m_network'] = num_corners


    print(f"Number of corners: {num_corners}")
    print(f"Connectiveness (average node degree): {avg_node_degree:.2f}")


    # Convert the network into a GeoDataFrame
    #gdf_nodes, gdf_edges = ox.graph_to_gdfs(G)

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 210
Connectiveness (average node degree): 4.71

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 82
Connectiveness (average node degree): 4.68

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 322
Connectiveness (average node degree): 5.10

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 133
Connectiveness (average node degree): 4.64

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 339
Connectiveness (average node degree): 4.88

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 215
Connectiveness (average node degree): 5.13

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 189
Connectiveness (average node degree): 5.08

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 108
Connectiveness (average node degree): 4.70

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 297
Connectiveness (average node degree): 4.91

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 184
Connectiveness (average node degree): 4.60

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 619
Connectiveness (average node degree): 5.32

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 346
Connectiveness (average node degree): 5.29

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 172
Connectiveness (average node degree): 4.87

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 197
Connectiveness (average node degree): 4.79

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 437
Connectiveness (average node degree): 5.11

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 214
Connectiveness (average node degree): 4.91

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 354
Connectiveness (average node degree): 5.22

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 419
Connectiveness (average node degree): 5.14

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 108
Connectiveness (average node degree): 4.70

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 346
Connectiveness (average node degree): 4.79

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 550
Connectiveness (average node degree): 5.30

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 289
Connectiveness (average node degree): 5.09

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 217
Connectiveness (average node degree): 5.03

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 449
Connectiveness (average node degree): 4.92

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 73
Connectiveness (average node degree): 4.75

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 324
Connectiveness (average node degree): 4.78

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 401
Connectiveness (average node degree): 5.28

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 391
Connectiveness (average node degree): 5.03

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 84
Connectiveness (average node degree): 4.16

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 8
Connectiveness (average node degree): 4.00

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 152
Connectiveness (average node degree): 5.43

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 89
Connectiveness (average node degree): 4.53

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 172
Connectiveness (average node degree): 5.14

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 148
Connectiveness (average node degree): 4.83

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 180
Connectiveness (average node degree): 5.44

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 198
Connectiveness (average node degree): 5.14

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 131
Connectiveness (average node degree): 4.68

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 73
Connectiveness (average node degree): 4.55

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 106
Connectiveness (average node degree): 4.89

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 114
Connectiveness (average node degree): 5.27

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 174
Connectiveness (average node degree): 4.96

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 7
Connectiveness (average node degree): 4.00

/tmp/ipykernel_1071/3182730832.py:11: FutureWarning: The expected order of coordinates in `bbox` will change in the v2.0.0 release to `(left, bottom, right, top)`.
  G = ox.graph_from_bbox(bbox=bbox,

Number of corners: 153
Connectiveness (average node degree): 5.12

In [20]:
gdf_nodes, gdf_edges = ox.graph_to_gdfs(G)

In [21]:
gdf_nodes.to_file("Data/gdf_nodes.geojson", driver="GeoJSON")
gdf_edges.to_file("Data/gdf_edges.geojson", driver="GeoJSON")

                                              osmid  oneway           name  \
u           v           key
21154171    304918610   0                  27891306   False     Sunny Bank
            1038682591  0    [701123738, 701123740]   False     Otley Road
21154172    530965904   0                 175770488   False  Bradford Road
            7101279799  0                 701124760   False     Otley Road
            520827289   0                 175770490   False  Bradford Road
...                                             ...     ...            ...
10857547687 530965889   0                  42526755   False            NaN
            2279776972  0                 218754456   False            NaN
11868890017 10857547666 0                1167492567   False            NaN
            567653109   0                  44750289   False            NaN
            10857547676 0                1167492567   False            NaN

                                 highway reversed   length  \
u           v           key
21154171    304918610   0    residential     True   95.749
            1038682591  0        primary     True   69.519
21154172    530965904   0          trunk    False   16.376
            7101279799  0        primary    False   36.781
            520827289   0          trunk     True   88.519
...                                  ...      ...      ...
10857547687 530965889   0        footway     True  176.863
            2279776972  0        footway    False  108.311
11868890017 10857547666 0        footway     True    7.716
            567653109   0        footway     True   88.367
            10857547676 0        footway    False   81.193

                                                                      geometry  \
u           v           key
21154171    304918610   0    LINESTRING (-1.77695 53.83014, -1.77714 53.830...
            1038682591  0    LINESTRING (-1.77695 53.83014, -1.77716 53.829...
21154172    530965904   0    LINESTRING (-1.78015 53.82773, -1.78009 53.82758)
            7101279799  0    LINESTRING (-1.78015 53.82773, -1.77980 53.82798)
            520827289   0    LINESTRING (-1.78015 53.82773, -1.78043 53.828...
...                                                                        ...
10857547687 530965889   0    LINESTRING (-1.78749 53.82770, -1.78734 53.827...
            2279776972  0    LINESTRING (-1.78749 53.82770, -1.78748 53.828...
11868890017 10857547666 0    LINESTRING (-1.78672 53.82915, -1.78663 53.82919)
            567653109   0    LINESTRING (-1.78672 53.82915, -1.78713 53.829...
            10857547676 0    LINESTRING (-1.78672 53.82915, -1.78693 53.829...

                              lanes    ref maxspeed bridge
u           v           key
21154171    304918610   0       NaN    NaN      NaN    NaN
            1038682591  0    [3, 2]  A6038   30 mph    NaN
21154172    530965904   0       NaN   A650   30 mph    NaN
            7101279799  0         3  A6038   30 mph    NaN
            520827289   0       NaN   A650   30 mph    NaN
...                             ...    ...      ...    ...
10857547687 530965889   0       NaN    NaN      NaN    NaN
            2279776972  0       NaN    NaN      NaN    NaN
11868890017 10857547666 0       NaN    NaN      NaN    NaN
            567653109   0       NaN    NaN      NaN    NaN
            10857547676 0       NaN    NaN      NaN    NaN

[492 rows x 11 columns]